
tasks:
  - init: yarn install && yarn run build
    command: yarn run start
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - gruntfuggly.todo-tree
github:
  prebuilds:
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addComment: true